baseURL: "https://bekalomidze.github.io"
title: Béka Lomidze
paginate: 20
theme: PaperMod

enableInlineShortcodes: true
enableRobotsTXT: true

taxonomies:
    tag: tags

#menu:
#    main:
#        - name: Research
#          url: /research/
#          weight: 1
#        - name: CV
#          url: /cv/
#          weight: 2

params:
    description: "I am a PhD student at the Bordeaux School of Economics under the supervision of Olivier Bargain & Jérôme Wittwer. I'm interested in social preferences, distributive justice and equity in health."
    author: Béka Lomidze
    #googleAnalyticsID: "G-97G4MZ4061"
    DateFormat: "January 2006"
    defaultTheme: dark
    hideFooter: true
    disableThemeToggle: true
    ShowShareButtons: false
    ShowReadingTime: false
    disableSpecial1stPost: true
    disableAnchoredHeadings: true
    ShowPostNavLinks: false
    ShowBreadCrumbs: false
    ShowCodeCopyButtons: true
    ShowRssButtonInSectionTermList: false
    ShowToc: false
    disableScrollToTop: true
    TocOpen: true
    ShowWordCount: false
    UseHugoToc: true
    comments: false
    math: true
    profileMode:
          enabled: true
          title : Béka Lomidze
          subtitle: "I am a PhD student at the [Bordeaux School of Economics](https://www.bse.u-bordeaux.fr/) under the supervision of [Olivier Bargain](https://sites.google.com/site/bargainoliv/) and [Jérôme Wittwer](https://smart-fhu.u-bordeaux.fr/Partenaires/Investigateurs-Partenaires/Pr-Jerome-Wittwer-i6651.html). I'm interested in social preferences, distributive justice and equity in health."
          imageUrl: "/Lomidze_crop.jpg"
          imageWidth: 200
          imageHeight: 200
          imageTitle: Béka Lomidze
          buttons:
            - name: Research
              url: /research/
            - name: Teaching
              url: /teaching/
            - name: Detailed CV
            #Put your CV below, it's in content
              url: /cv/BekaLOMIDZE_CV.pdf
    socialIcons:
        - name: Email
          url: mailto:beka.lomidze@u-bordeaux.fr
        - name: LinkedIn
          url: https://fr.linkedin.com/in/beka-lomidze
        #- name: GitHub
        #  url: https://github.com/colmate
        - name: Location
          url: /location/

    assets:
        disableHLJS: true
        disableScrollBarStyle: true
    cover:
        hiddenInList: true
        hiddenInSingle: true
    label:
      text: "Beka Lomidze"
      #Put your icon below, it's in content
      icon: /favicon.ico
      iconHeight: 18

markup:
    goldmark:
        renderer:
            unsafe: true
    highlight:
        guessSyntax: true
        style: autumn
    tableOfContents:
        endLevel: 2
        ordered: false
        startLevel: 2
